[book]
title = "El llenguatge de programació Rust"
authors = ["Steve Klabnik", "Carol Nichols", "Amb la col·laboració de la Comunitat Rust"]

[output.html]
additional-css = ["ferris.css", "theme/2018-edition.css"]
additional-js = ["ferris.js"]
git-repository-url = "https://github.com/rust-lang/book"
