[book]
title = "El llenguatge de programació Rust"
authors = ["Steve Klabnik", "Carol Nichols", "Amb la col·laboració de la Comunitat Rust"]
language = "ca"
src = "translation"

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]
max_depth = 3

[output.html]
additional-css = ["ferris.css", "theme/2018-edition.css"]
additional-js = ["ferris.js"]
git-repository-url = "https://github.com/rust-lang/book"

